# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: mcskim04@gmail.com
author_name: Minchan Kim
create_claude_symlink: true
create_gemini_symlink: true
has_ai_rules: true
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: jupytercon2025-extension-workshop
project_short_description: A JupyterLab extension that displays a random image and
    caption.
python_name: jupytercon2025_extension_workshop
repository: https://github.com/m1nce/jupytercon2025-extension-workshop
test: true

